### DISCUSSION TITLE
docs/cli/build

### DISCUSSION THREAD

**Discussion by giscus** [gogf/gf-site#115] [General]
# docs/cli/build

使用GoFrame框架进行交叉编译。通过gf build命令，可以快速生成带有当前Go版本、GoFrame版本、Git Commit等信息的可执行文件。支持同时从命令行和配置文件指定参数，满足不同操作系统和平台的编译需求，为开发者提供便捷的构建解决方案。

https://goframe.org/docs/cli/build

**Comment by darkmice** [comment]
gf build 如何更换编译main.go 入口

**Reply by gqcn** [reply]
`gf build my.go`

**Comment by Ling1992** [comment]
packSrc: "manifest"
多环境编译下，如何切换配置文件的问题 。 
manifest/config/config.yaml
manifest/config/test-config.yaml
manifest/config/dev-config.yaml
manifest/config/pro-config.yaml

**Comment by luckxgo** [comment]
gfcli:
  build:
    name:     "axure_client"
    arch:     "arm"
    system:   "darwin"
    mod:      "none"
    packSrc:  "resource,manifest"
    version:  "v1.0.1"
    extra:    ""

按照这个配置，无法打包mac  arm包

**Reply by luckxgo** [reply]
要写 arm64 没啥问题了

**Comment by LanceAdd** [comment]
使用```gf build```进行交叉编译时，可以在hack/config中添加`extra: "-ldflags=\"-s -w\""`参数，从而达到去除调试信息减少可执行文件的作用
```
gfcli:
  build:
    name: "quick-demo"
    arch: "amd64"
    system: "linux,darwin,windows"
    packSrc: "resource,manifest"
    version: "v1.0.0"
    path: "target"
    extra: "-ldflags=\"-s -w\""
```
然后可以使用 upx 对可执行文件进行压缩
可以使用`upx --brute xxx.exe`尽最大可能压缩
