### DISCUSSION TITLE
docs/core/gdb-sharding-schema

### DISCUSSION THREAD

**Discussion by giscus** [gogf/gf-site#187] [General]
# docs/core/gdb-sharding-schema

GoFrame ORM分库特性提供了灵活高效的库分片功能，支持自定义分库规则，轻松实现数据库水平扩展。

https://goframe.org/docs/core/gdb-sharding-schema

**Comment by pihc** [comment]
这里的使用Hook实现动态分库，需要手动添加 Hook方法 model := g.Model("user").Hook(hook)，每次都手动写的话还挺麻烦的，有可能会导致遗漏，请问如何全局动态切库，我现在使用的方式是修改 dao层的生成模板
```
gfcli:
  gen:
    dao:
#      # 多租户默认库（column/db模式都要打开）
#      - <<: *commonGenConfig
#        group: "default"
#        tables: *commonTables
#      # 多租户db模式 贴牌库（表结构暂和主库放在一块方生成dao方便开发）
#      - <<: *commonGenConfig
#        tplDaoInternalPath: "./internal/library/gftenant/tenant.tpl" # 模版里添加了动态切库的逻辑
#        group: "tenant"
#        tablesEx: *commonTables
```
在这个模板中  "./internal/library/gftenant/tenant.tpl" 修改了 DB 方法
```
// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *{TplTableNameCamelCase}Dao) DB(ctx context.Context) gdb.DB {
	if db:=gftenant.Init(ctx);db!=nil{
        return db
    }
	return g.DB(dao.group)
}
```
```
// Init 初始化当前DB链接，分组和dbname同名
func Init(ctx context.Context) gdb.DB {
	tenantId := GetTenant(ctx)
	dbName := fmt.Sprintf("tenant_%d", tenantId)

	if ll := gdb.GetConfig(dbName); len(ll) == 0 {
		gdb.SetConfigGroup(dbName, gdb.ConfigGroup{
			gdb.ConfigNode{
				Debug: m.Debug,
				Link:  fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local", m.DbAccount, m.DbPass, m.DbAddr, m.DbPort, m.DbName),
				Type:  "mysql",
				Name:  dbName, // 这里补一个Name,否则sql打印会有问题
			},
		})
	}

	return g.DB(dbName)
}
```
这样去实现动态切库的，这种方案感觉对框架的侵入性有点大，怕后面升级 dao层的模板改了，我这里也需要相应的去修改逻辑，请问有没有更好的解决方案
