### DISCUSSION TITLE
docs/cli/gen-enums

### DISCUSSION THREAD

**Discussion by giscus** [gogf/gf-site#29] [General]
# docs/cli/gen-enums

该功能特性为 实验性特性，从 v2.4 版本开始提供。

https://goframe.org/docs/cli/gen-enums

**Comment by anban9616** [comment]
# 实际使用跟文档描述的有些出入。
```
  gen:
    enums:
      src: "internal/consts"
      path: "internal/boot/boot_enums.go"
```
期望的是检索internal/consts目录下的文件，然后生成到internal/boot/boot_enums.go
实际的是检索internal/consts目录下的文件，然后生成到了internal/consts/internal/boot/boot_enums.go
